Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run($CmdLine[1])
WinWait("Mozilla Build Setup: License Agreement","")
If Not WinActive("Mozilla Build Setup: License Agreement","") Then WinActivate("Mozilla Build Setup: License Agreement","")
WinWaitActive("Mozilla Build Setup: License Agreement","")
MouseMove(388,257)
MouseDown("left")
MouseUp("left")
WinWait("Mozilla Build Setup: Installation Folder","")
If Not WinActive("Mozilla Build Setup: Installation Folder","") Then WinActivate("Mozilla Build Setup: Installation Folder","")
WinWaitActive("Mozilla Build Setup: Installation Folder","")
Send("{BACKSPACE}d{SHIFTDOWN};{SHIFTUP}\mozilla-build")
MouseDown("left")
MouseUp("left")
WinWait("Mozilla Build Setup","This will overwrite")
If Not WinActive("Mozilla Build Setup","This will overwrite") Then WinActivate("Mozilla Build Setup","This will overwrite")
WinWaitActive("Mozilla Build Setup","This will overwrite")
Send("{ENTER}")
WinWait("Mozilla Build Setup: Completed","")
If Not WinActive("Mozilla Build Setup: Completed","") Then WinActivate("Mozilla Build Setup: Completed","")
WinWaitActive("Mozilla Build Setup: Completed","")
MouseMove(362,258)
MouseDown("left")
MouseUp("left")

