Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run($CmdLine[1])
WinWait("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","Welcome to the Setup Wizard")
If Not WinActive("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","Welcome to the Setup Wizard") Then WinActivate("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","Welcome to the Setup Wizard")
WinWaitActive("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","Welcome to the Setup Wizard")
MouseMove(616,499)
MouseDown("left")
MouseUp("left")
MouseMove(346,418)
MouseDown("left")
MouseUp("left")
MouseMove(608,493)
MouseDown("left")
MouseUp("left")
MouseDown("left")
MouseUp("left")
MouseMove(295,275)
MouseDown("left")
MouseMove(11,235)
MouseUp("left")
Send("d{SHIFTDOWN};{SHIFTUP}\sdks\v7.0")
MouseMove(469,341)
MouseDown("left")
MouseUp("left")
MouseMove(400,378)
MouseDown("left")
MouseUp("left")
MouseMove(605,488)
MouseDown("left")
MouseUp("left")
MouseMove(68,111)
MouseDown("left")
MouseUp("left")
MouseMove(62,161)
MouseDown("left")
MouseUp("left")
MouseMove(101,285)
MouseDown("left")
MouseUp("left")
MouseMove(613,510)
MouseDown("left")
MouseUp("left")
MouseMove(616,504)
MouseDown("left")
MouseUp("left")
MouseDown("left")
MouseUp("left")
WinWait("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","The selected modifications are complete.")
If Not WinActive("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","The selected modifications are complete.") Then WinActivate("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","The selected modifications are complete.")
WinWaitActive("[REGEXPTITLE:.*SDK.* and .NET Framework 3.5 Service Pack 1]","The selected modifications are complete.")
MouseMove(175,299)
MouseDown("left")
MouseUp("left")
MouseMove(685,496)
MouseDown("left")
MouseUp("left")

